// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo5s9GoknIKATowuDt6pc6NyKWSQgBu6c',
    appId: '1:622846946570:web:ee401d5010459250879ef3',
    messagingSenderId: '622846946570',
    projectId: 'fir-app-bd61e',
    authDomain: 'fir-app-bd61e.firebaseapp.com',
    storageBucket: 'fir-app-bd61e.appspot.com',
    measurementId: 'G-DEKSYK6JRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFaiCzMRQ9mAuMOiM9aSknh85Tb6eBTzo',
    appId: '1:622846946570:android:5fb1c543d177638b879ef3',
    messagingSenderId: '622846946570',
    projectId: 'fir-app-bd61e',
    storageBucket: 'fir-app-bd61e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsJjsCW1RSCSeohIvPSqBAcBdRq1t_2P4',
    appId: '1:622846946570:ios:9dd697be25e7b3a1879ef3',
    messagingSenderId: '622846946570',
    projectId: 'fir-app-bd61e',
    storageBucket: 'fir-app-bd61e.appspot.com',
    iosBundleId: 'com.example.firebaseDemoApp',
  );
}
